const groceryinventory = [
    {
      "item": "mango",
      "price": 2.99,
      "description": "fruit",
      "units":"15",
      "quantity":"75",
      "isPurchased": true,
      "brand": "Donavan's favorite",
    },
    {
      "item": "plantains",
      "price": .50,
      "description": "fruit",
      "units":"10",
      "quantity":"50",
      "isPurchased": true,
      "brand": "plenty of plantains",
    },
    {
      "item": "bananas",
      "price": .75,
      "description": "fruit",
      "units":"10",
      "quantity":"50",
      "isPurchased": true,
      "brand": "ThisIshIs B-A-N-A-N-A-S",
    },
    {
      "item": "aloe",
      "price": 3.99,
      "description": "plant",
      "units":"10",
      "quantity":"50",
      "isPurchased": true,
      "brand": "everything aloe`",
    },
    {
      "item": "green apples",
      "price": 2.99,
      "description": "fruit",
      "units":"15",
      "quantity":"75",
      "isPurchased": true,
      "brand": "natural sour-patch",
    },
    {
     "item": "jack-fruit",
     "price": 8.99,
     "description": "fruit",
     "units":"10",
     "quantity":"50",
     "isPurchased": true,
     "brand": "jackie-o fruit",
    },
    {
      "item": "field-peas",
      "price": 5.99,
      "description": "vegetables",
      "units":"15",
      "quantity":"75",
      "isPurchased": true,
      "brand": "peas not beans",
    },
    {
      "item": "butter-beans",
      "price": 4.99,
      "description": "vegetables",
      "units":"10",
      "quantity":"50",
      "isPurchased": true,
      "brand": "home-comfort",
    },
    {
      "item": "okra",
      "price": 1.99,
      "description": "vegetables",
      "units":"10",
      "quantity":"50",
      "isPurchased": true,
      "brand": "What's poppin'slime",
    },
    {
      "item": "onions",
      "price": 2.99,
      "description": "vegetables",
      "units":"20",
      "quantity":"100",
      "isPurchased": true,
      "brand": "cry-here eat here onions",
    },
    {
      "item": "maggi-cubes",
      "price": 1.99,
      "description": "seasonings",
      "units":"10",
      "quantity":"50",
      "isPurchased": true,
      "brand": "all-necessary all-purpose",
    },
    {
      "item": "peppers",
      "price": 2.99,
      "description": "vegetables",
      "units":"20",
      "quantity":"100",
      "isPurchased": true,
      "brand": "peppin' peppers",
    },
    {
      "item": "mushrooms",
      "price": 1.99,
      "description": "vegetables",
      "units":"10",
      "quantity":"50",
      "isPurchased": true,
      "brand": "everybody-loves shrooms",
    },
    {
      "item": "alkaline-water",
      "price": 4.99,
      "description": "fruit",
      "units":"40",
      "quantity":"200",
      "isPurchased": true,
      "brand": "neva-sick aqua",
    },
    {
      "item": "seamoss",
      "price": 19.99,
      "description": "vegetables",
      "units":"5",
      "quantity":"25",
      "isPurchased": true,
      "brand": "sebimosse`",
    },
    {
      "item": "pineapple",
      "price": 2.99,
      "description": "fruit",
      "units":"10",
      "quantity":"50",
      "isPurchased": true,
      "brand": "pineapple-bliss",
    },
    {
      "item": "spinach",
      "price": .99,
      "description": "vegetables",
      "units":"20",
      "quantity":"100",
      "isPurchased": true,
      "brand": "grass-is-greener",
    },
    {
      "item": "eggs",
      "price": 1.99,
      "description": "poultry",
      "units":"5",
      "quantity":"50",
      "isPurchased": true,
      "brand": "Foghorn-Leghorn eggs",
    },
    {
      "item": "sugar-cane",
      "price": 1.99,
      "description": "fruit",
      "units":"10",
      "quantity":"50",
      "isPurchased": true,
      "brand": "pure-cane",
    },
    {
      "item": "black-berries",
      "price": .99,
      "description": "fruit",
      "units":"10",
      "quantity":"50",
      "isPurchased": true,
      "brand": "fresh-organic",
    },
    {
      "item": "pre-made epis",
      "price": 2.99,
      "description": "seasonings",
      "units":"10",
      "quantity":"50",
      "isPurchased": true,
      "brand": "fresh-deli",
    },
  ];
  
  export default groceryinventory;